# CircleCIのビルドを止める権限がなかったので
# ひとまずエラーが出ない最小の設定に変更した。
# CircleCIのビルドを停止したらこのファイルは削除してよい。

version: 2.1

jobs:
  noop:
    docker:
      - image: busybox
    steps:
      - run: echo ok

workflows:
  version: 2

  build:
    jobs:
      - noop